<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Bienvenido</title>
	<link rel="stylesheet" href="<?php echo APP_URL;?>views/layouts/default/css/normalize.min.css">
	<link rel="stylesheet" href="<?php echo APP_URL;?>views/layouts/default/css/bootstrap.min.css">
	<link rel="stylesheet" href="<?php echo APP_URL;?>views/layouts/default/css/main.css">
	<script src="<?php echo APP_URL; ?> views/layouts/default/js/vendor/modernizr-2.8.3.min.js"></script>
</head>
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="<?php echo APP_URL;?>/views/layouts/default/js/vendor/jquery-1.11.2.min.js"><\/script>')</script>
    <script src="<?php echo APP_URL;?>views/layouts/default/js/vendor/bootstrap.min.js"></script>
    <script src="<?php echo APP_URL;?>views/layouts/default/js/plugins.js"></script>
    <script src="<?php echo APP_URL;?>views/layouts/default/js/main.js"></script>

        <!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
        <script>
            (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
            function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
            e=o.createElement(i);r=o.getElementsByTagName(i)[0];
            e.src='//www.google-analytics.com/analytics.js';
            r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
            ga('create','UA-XXXXX-X','auto');ga('send','pageview');
        </script>
<body>
<div class="container">
		<div class="row">
			<header>
				
			</header>
		</div>
		<div class="row">
			<nav class="navbar navbar-default navbar-static-top" role="navigation">
		    <!-- Brand and toggle get grouped for better mobile display -->
			    <div class="navbar-header">
			      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex6-collapse">
			        <span class="sr-only">Desplegar</span>
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
			      </button>
			      <a class="navbar-brand" href="#"><b>Sistema de control</b></a>
			    </div>

			    <div class="collapse navbar-collapse navbar-ex6-collapse">
			      <ul class="nav navbar-nav">
			        	<li><a href="<?php echo APP_URL; ?>">Home</a></li>
						<li><a href="<?php echo APP_URL; ?>users">Usuarios</a></li>
						<li><a href="<?php echo APP_URL; ?>categories">Categorias</a></li>
						<li><a href="<?php echo APP_URL; ?>transactions">Transacciones</a></li>
						<li><a href="<?php echo APP_URL; ?>accounts">Cuentas</a></li>
						<li><a href="<?php echo APP_URL; ?>users/logout">Cerrar sesion</a></li>
			      </ul>
			    </div>
  			</nav>
		</div>
		<div class="row" style="z-index:-1;">
			<div class="col-md-12" style=" margin:15px;">
